# This file was generated by GoReleaser. DO NOT EDIT.
cask "fastdeploy-client" do
  name "fastdeploy-client"
  desc "CLI multiplataforma para despliegues automáticos y rápidos de aplicaciones"
  homepage "https://github.com/jairoprogramador/fastdeploy-client"
  version "0.0.8"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fdc"

  on_macos do
    on_intel do
      url "https://github.com/jairoprogramador/fastdeploy-client/releases/download/v#{version}/fastdeploy-client_darwin_amd64.tar.gz"
      sha256 "1f70a26971d6b206c4fbede0c75f90ac9089b715c62f99507ea23be66197e518"
    end
    on_arm do
      url "https://github.com/jairoprogramador/fastdeploy-client/releases/download/v#{version}/fastdeploy-client_darwin_arm64.tar.gz"
      sha256 "5bf7096c7aa16c99461944faf9e5ae918b50cc88804b57d953a7eabe7b6e0841"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jairoprogramador/fastdeploy-client/releases/download/v#{version}/fastdeploy-client_linux_amd64.tar.gz"
      sha256 "966d9388276bcec254d71122ff561a770adf567790dd418b41eb9413d5299625"
    end
    on_arm do
      url "https://github.com/jairoprogramador/fastdeploy-client/releases/download/v#{version}/fastdeploy-client_linux_arm64.tar.gz"
      sha256 "5c21dc9a62e87e94088a99fbb23e0cf470398831d7c067dcb977db7ba6c320de"
    end
  end

  # No zap stanza required
end
