# This file was generated by GoReleaser. DO NOT EDIT.
cask "vex" do
  name "vex"
  desc "CLI multiplataforma para despliegues automáticos y rápidos de aplicaciones"
  homepage "https://github.com/jairoprogramador/vex-client"
  version "0.0.16"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vex"

  on_macos do
    on_intel do
      url "https://github.com/jairoprogramador/vex-client/releases/download/v#{version}/vex_darwin_amd64.tar.gz"
      sha256 "f7ac614fbd988460d0872ad18cb8b00ab8dbcae0ffb2a18e9194ecdd2a315d7c"
    end
    on_arm do
      url "https://github.com/jairoprogramador/vex-client/releases/download/v#{version}/vex_darwin_arm64.tar.gz"
      sha256 "1005490128a5a39046aaad2a74c3469f03db334d088ab036860efb0f300720af"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jairoprogramador/vex-client/releases/download/v#{version}/vex_linux_amd64.tar.gz"
      sha256 "e8ea38bec048f47212dd2421bce5bdc81f9c869b2761dd428c872ee1e9f547f3"
    end
    on_arm do
      url "https://github.com/jairoprogramador/vex-client/releases/download/v#{version}/vex_linux_arm64.tar.gz"
      sha256 "789fc9bef958a382674bbddc2538ae95360c8da894bf5d9c74c774b66b128ba3"
    end
  end

  # No zap stanza required
end
