# This file was generated by GoReleaser. DO NOT EDIT.
cask "vex" do
  version "0.0.25"

  on_macos do
    on_intel do
      url "https://github.com/jairoprogramador/vex/releases/download/v#{version}/vex_darwin_amd64.tar.gz"
      sha256 "eb89f206fea791bb00f9ae7b3d8e4f183ae146e31a695408ded246b05b4f06a5"
    end
    on_arm do
      url "https://github.com/jairoprogramador/vex/releases/download/v#{version}/vex_darwin_arm64.tar.gz"
      sha256 "baa63ba70dba19514e92753c9ef9ad092db1559697ac888c53938be6c285222c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jairoprogramador/vex/releases/download/v#{version}/vex_linux_amd64.tar.gz"
      sha256 "d07b80d58187550e91c6ea0212d1d6f6d5a361602bcbe7f00267e48a942756fb"
    end
    on_arm do
      url "https://github.com/jairoprogramador/vex/releases/download/v#{version}/vex_linux_arm64.tar.gz"
      sha256 "fa112e4d42c479048655038fd4d8e9eab057fa7726aff181151e59bc546be62e"
    end
  end

  name "vex"
  desc "CLI multiplataforma para despliegues automáticos y rápidos de aplicaciones"
  homepage "https://github.com/jairoprogramador/vex"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vex"

  # No zap stanza required

end
